### ISSUE TITLE
zip slip error

### ISSUE THREAD

**Issue by okundzich** [openrewrite/rewrite-analysis#48]
zip slip error
[Slack Message](https://moderneinc.slack.com/archives/C01VADFPJQZ/p1709561371247299)

<img width="1030" alt="image" src="https://github.com/openrewrite/rewrite-analysis/assets/26604045/7d99b178-62d4-40f3-948f-13ffc14c9dc7">

**Comment by JLLeitschuh** [comment]
That's really interesting and unexpected. That class is a transitive dependency of `rewrite-analysis`

**Comment by knutwannheden** [comment]
AFAICT this was resolved. I suspect this was caused by a deployment error due to a Sonatype outage.
